#!/usr/bin/env python
# ===--- project_precommit_check ------------------------------------------===
#
#  This source file is part of the Swift.org open source project
#
#  Copyright (c) 2014 - 2017 Apple Inc. and the Swift project authors
#  Licensed under Apache License v2.0 with Runtime Library Exception
#
#  See https://swift.org/LICENSE.txt for license information
#  See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
#
# ===----------------------------------------------------------------------===

import sys
import os
import argparse
import platform
import json

import common

script_path = os.path.dirname(os.path.realpath(__file__))
project_list = os.path.join(script_path, 'projects.json')
runner_path = os.path.join(script_path, 'runner.py')
supported_configs = {
    'Darwin': {
        '3.0': {
            'version': 'Apple Swift version 3.0 '
                       '(swiftlang-800.0.46.2 clang-800.0.38)\n'
                       'Target: x86_64-apple-macosx10.9\n',
            'description': 'Xcode 8.0 (contains Swift 3.0)',
            'branch': 'swift-3.0-branch'
        },
        '3.1': {
            'version': 'Apple Swift version 3.1 '
                       '(swiftlang-802.0.53 clang-802.0.42)\n'
                       'Target: x86_64-apple-macosx10.9\n',
            'description': 'Xcode 8.3.2 (contains Swift 3.1)',
            'branch': 'swift-3.0-branch'
        },
        '4.0': {
            'version': 'Apple Swift version 4.0 '
                       '(swiftlang-900.0.65.2 clang-900.0.37)\n'
                       'Target: x86_64-apple-macosx10.9\n',
            'description': 'Xcode 9.0.1 (contains Swift 4.0)',
            'branch': 'swift-4.0-branch'
        },
        '3.2': {
            'version': 'Apple Swift version 4.0.3 '
                       '(swiftlang-900.0.74.1 clang-900.0.39.2)\n'
                       'Target: x86_64-apple-macosx10.9\n',
            'description': 'Xcode 9.2 (contains Swift 3.2 compatibility mode)',
            'branch': 'swift-4.0-branch'
        },
        '4.0.3': {
            'version': 'Apple Swift version 4.0.3 '
                       '(swiftlang-900.0.74.1 clang-900.0.39.2)\n'
                       'Target: x86_64-apple-macosx10.9\n',
            'description': 'Xcode 9.2 (contains Swift 4.0.3)',
            'branch': 'swift-4.0-branch'
        },
        '4.1': {
            'version': 'Apple Swift version 4.1 '
                       '(swiftlang-902.0.48 clang-902.0.37.1)\n'
                       'Target: x86_64-apple-darwin17.7.0\n',
            'description': 'Xcode 9.3 (contains Swift 4.1)',
            'branch': 'swift-4.1-branch'
        },
        '4.2': {
            'version': 'Apple Swift version 4.2 '
                       '(swiftlang-1000.0.16.9 clang-1000.10.25.3)\n'
                       'Target: x86_64-apple-darwin17.7.0\n',
            'description': 'Xcode 10 Beta 2 (contains Swift 4.2)',
            'branch': 'swift-4.2-branch'
        }
    },
    # NOTE: Linux isn't fully supported yet
    'Linux': {
        '3.0': {
            'version': 'Swift version 3.0 '
                       '(swift-3.0-RELEASE)\n'
                       'Target: x86_64-unknown-linux-gnu\n',
            'description': 'swift-3.0-RELEASE toolchain',
            'branch': 'swift-3.0-branch'
        },
        '3.1': {
            'version': 'Swift version 3.1 '
                       '(swift-3.1-RELEASE)\n'
                       'Target: x86_64-unknown-linux-gnu\n',
            'description': 'swift-3.1-RELEASE toolchain',
            'branch': 'swift-3.0-branch'
        }
    }
}


def parse_args():
    parser = argparse.ArgumentParser(
        description='Check a project for inclusion in the Swift source compatibility test suite'
    )
    parser.add_argument('project',
                        help='the project to test, specified by the "path" index field')
    parser.add_argument('--earliest-compatible-swift-version',
                        metavar='VERSION',
                        help='the Swift version mode to check, including decimal point (e.g. 3.0)',
                        required=True)
    parser.add_argument('--swiftc',
                        metavar='PATH',
                        help='swiftc executable')
    return parser.parse_args()


def validate(project_path, compatibility_version):
    common.debug_print("--- Validating %s Swift version %s compatibility ---" % (project_path, compatibility_version))
    index = json.loads(open(project_list).read())
    project = next((p for p in index if p['path'] == project_path), None)
    if not project:
        common.debug_print("error: Unable to find %s in project index ---" % project_path)
        exit(1)
    try:
        compatibility_dict = {version['version']: version for version in project['compatibility']}
        compatibility_dict[compatibility_version]
    except (IndexError, KeyError, TypeError) as e:
        common.debug_print("error: Unable to find %s Swift version %s compatibility in project index ---" % (project_path, compatibility_version))
        common.debug_print("note: Please add a version entry for %s to the `compatibility` field for %s in the project index or check against a version that has already been added ---" % (compatibility_version, project_path))
        raise
    common.debug_print("--- Project configured to be compatible with Swift %s ---" % compatibility_version)

    common.debug_print("--- Checking %s platform compatibility with %s ---" % (project_path, platform.system()))
    if not platform.system() in project['platforms']:
        common.debug_print("error: %s is not configured to be compatible with %s ---" % (project_path, platform.system()))
        common.debug_print("-- Add %s to the platforms list for %s ---" % (platform.system(), project_path))
        exit(1)
    common.debug_print("--- Platform compatibility check succeeded ---")


def is_correct_swift_version(swiftc, compatibility_version):
    common.debug_print("--- Checking installed Swift version ---")
    swift_version = common.check_execute_output([swiftc, '--version'])
    try:
        expected_swift_version = supported_configs[platform.system()][compatibility_version]['version']
    except KeyError:
        common.debug_print("error: Project configured for unsupported platform or Swift version")
        raise
    error_msg = "error: please select {description}".format(
        description=supported_configs[platform.system()][compatibility_version]['description']
    )
    if swift_version != expected_swift_version:
        common.debug_print("--- Version check failed ---")
        common.debug_print("Expected version:\n" + expected_swift_version)
        common.debug_print("Current version:\n" + swift_version)
        common.debug_print(error_msg)
        return False
    common.debug_print("--- Version check succeeded ---")
    return True


def check(project, swift_branch, swiftc, compatibility_version):
    if platform.system() == 'Darwin':
        common.debug_print("--- Locating swiftc executable ---")
        swiftc = common.check_execute_output(['xcrun', '-f', 'swiftc']).strip()
    if not swiftc:
        common.debug_print('error: please specify --swiftc')
        return 1
    swiftc = os.path.abspath(swiftc)
    if not is_correct_swift_version(swiftc, compatibility_version):
        return 1
    runner_command = [
        runner_path,
        '--swift-branch', swift_branch,
        '--swiftc', swiftc,
        '--projects', project_list,
        '--include-repos', 'path == "%s"' % project,
        '--include-versions', 'version == "%s"' % compatibility_version,
        '--include-actions', 'action.startswith("Build")',
    ]
    common.debug_print("--- Executing build actions ---")
    try:
        common.check_execute(runner_command, timeout=3600)
    except common.ExecuteCommandFailure:
        common.debug_print("--- Encountered failures. Check .log files in current directory for details ---")
        return 1
    common.debug_print("--- %s checked successfully against Swift %s ---" % (project, compatibility_version))
    return 0


def main():
    os.chdir(os.path.dirname(__file__))
    args = parse_args()
    common.debug_print('** CHECK **')
    validate(args.project, args.earliest_compatible_swift_version)
    config = supported_configs[platform.system()][args.earliest_compatible_swift_version]
    common.set_swift_branch(config['branch'])
    return check(args.project, config['branch'], args.swiftc, args.earliest_compatible_swift_version)

if __name__ == '__main__':
    sys.exit(main())

